// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knptvvvzctyxnohcnekt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtucHR2dnZ6Y3R5eG5vaGNuZWt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNjI0OTEsImV4cCI6MjA1NzkzODQ5MX0.itqDJevJpkCwRdGz7lnUW-uiTnabaCUpt_uSDVh2zDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);